export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAILURE = "USER_SIGNIN_FAILURE";

export const CHECK_USER_REQUEST = "CHECK_USER_REQUEST";
export const CHECK_USER_SUCCESS = "CHECK_USER_SUCCESS";
export const CHECK_USER_FAILURE = "CHECK_USER_FAILURE";

export const SET_USER_TOKEN = "SET_USER_TOKEN";
export const LOGOUT_USER = "LOGOUT_USER";


export const SET_USER_MOBILE = "SET_USER_MOBILE";
export const SET_USER_PASSWORD = "SET_USER_PASSWORD";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";






