export const HIGHLIGHT_CHUNK = "HIGHLIGHT_CHUNK";

export const SET_POST_ACTIVE_LIBRARY_NAME = "SET_POST_ACTIVE_LIBRARY_NAME";
export const SET_POST_ACTIVE_DOCUMENT_ID = "SET_POST_ACTIVE_DOCUMENT_ID";

export const SET_POST_ACTIVE_PAGE = "SET_POST_ACTIVE_PAGE";


export const SET_POST_RECIPIENT = "SET_POST_RECIPIENT";
export const SET_POST_SENDER = "SET_POST_SENDER";
export const SET_POST_DELIVERY = "SET_POST_DELIVERY";
export const SET_POST_WEIGHT = "SET_POST_WEIGHT";
export const SET_POST_ACTIVE_SERVICE = "SET_POST_ACTIVE_SERVICE";
export const SET_POST_ACTIVE_ADDITIONAL_SERVICE = "SET_POST_ACTIVE_ADDITIONAL_SERVICE";
export const SET_POST_SERVICE_COST = "SET_POST_SERVICE_COST";
export const SET_POST_ADDITIONAL_SERVICE_COST = "SET_POST_ADDITIONAL_SERVICE_COST";

export const RESET_POST_STATE = "RESET_POST_STATE";

